version: '2.1'

services:

  website:
    image: website
    build:
      context: ./src/Market.Website
      dockerfile: Dockerfile
    volumes:
      - ./src/Market.Website:/app
#      - ./src/Market.Website/node_modules:/app/node_modules
    ports:
      - "127.0.0.1:5000:4200"
  
  market_realtime:
    image: market_realtime
    build:
      context: ./src/Market.RealTime
      dockerfile: Dockerfile
    volumes:
      - ./src/Market.RealTime/node_modules:/app/node_modules
    ports:
      - "127.0.0.1:5001:1337"
    environment:
      redis_url: redis://redis

  market_api:
    image: market_api
    build:
      context: ./src/Market.Api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5002:5000"
    environment:
      LogLevel: Information
      MongoUrl: mongodb://mongodb:27017
      MongoDatabase: stockmarket

  market:
    image: market
    build:
      context: ./src/Market
      dockerfile: Dockerfile
    environment:
      LogLevel: Information
      QueueHostName: queue
      MongoUrl: mongodb://mongodb:27017
      MongoDatabase: stockmarket
      RedisHost: redis

  traderbot:
    image: traderbot
    build:
      context: ./src/TraderBot
      dockerfile: Dockerfile
    environment:
      LogLevel: Warning
      QueueHostName: queue
  
  queue:
    image: rabbitmq:alpine

  mongodb:
    image: mongo

  redis:
    image: redis
