version: '2.1'

services:
  
  market_realtime:
    image: market_realtime
    build:
      context: ./src/Market.RealTime
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      redis_url: redis://redis

  market_api:
    image: market_api
    build:
      context: ./src/Market.Api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      LogLevel: Information
      MongoUrl: mongodb://mongodb:27017
      MongoDatabase: stockmarket

  market:
    image: market
    build:
      context: ./src/Market
      dockerfile: Dockerfile
    environment:
      LogLevel: Information
      QueueHostName: queue
      MongoUrl: mongodb://mongodb:27017
      MongoDatabase: stockmarket
      RedisHost: redis

  traderbot:
    image: traderbot
    build:
      context: ./src/TraderBot
      dockerfile: Dockerfile
    environment:
      LogLevel: Warning
      QueueHostName: queue
  
  queue:
    image: rabbitmq:alpine

  mongodb:
    image: mongo

  redis:
    image: redis
