version: '2.1'

services:
  
  market:
    image: market
    build:
      context: ./src/Market
      dockerfile: Dockerfile
    environment:
      QueueHostName: queue
      MongoUrl: mongodb://mongodb:27017

  traderbot:
    image: traderbot
    build:
      context: ./src/TraderBot
      dockerfile: Dockerfile
    environment:
      QueueHostName: queue
  
  queue:
    image: rabbitmq:alpine

  mongodb:
    image: mongo
