version: '2.1'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./sim-stock-market.sln && dotnet publish ./sim-stock-market.sln -c Release -o ./obj/Docker/publish"
